import type { Metadata } from "next";
import ContentPage, { type Content } from "@/components/ContentPage";

export const metadata: Metadata = {
  title: "Brawl Draft FAQ — Brawl Draft",
  description: "Answers about Brawl Draft: what it does, entering your player tag, blind pick vs snake draft, how the model reads an unfinished draft, personalizing to your roster and the season's free brawlers, and where the data comes from.",
  alternates: { canonical: "/faq" },
};

// Prose lives here as data so ContentPage owns all the layout and typography; every figure
// quoted below was checked against docs/metrics.json and the engine source.
const content: Content = {
  title: "Brawl Draft FAQ",
  intro: "Brawl Draft is a free draft assistant for Brawl Stars Ranked. You set the map, tap the bans and picks as they happen, and it ranks what you should take next using real ranked match data plus a trained win-probability model.\n\nThese are the questions that come up most. If something here does not match what the board is actually doing, the board is the source of truth and this page needs fixing.",
  sections: [
    { heading: "What is Brawl Draft?", body: "It is a draft board that mirrors your live Ranked draft. You choose the map, mark the six bans, mark each pick as it happens, and after every tap it re-ranks every remaining brawler for the seat you are in.\n\nThe ranking is not a single tier list. Each suggestion is scored by fusing several signals: how the brawler performs on that specific map, how it pairs with the allies already locked in, how it matches up against the enemy brawlers already revealed, whether its class fits the mode, and a neural win-probability model trained on collected ranked matches. The top recommendation breaks every one of those components out as its own bar, and the runners-up condense them to the strongest few, so you can see why a pick is ranked where it is instead of trusting a number.\n\nIt also flags composition holes as you draft (no frontline, no long range, three of the same class, enemy is tank-heavy) and builds a game plan as your team fills in — a rule-based read on how to play the comp, plus a measured one: the head-to-head grid of your brawlers against theirs, each of yours on that map, and your pairs together, each shown with the effective sample behind it. Once both teams are complete the model adds its win probability for the finished draft." },
    { heading: "How do I use it during an actual draft?", body: "Pick your map from the dropdown at the top before the draft starts, and set the first-pick toggle to match who is picking first. Then follow the banner: it tells you whether the board is expecting a ban, your pick, or the enemy's pick.\n\nTap a brawler to fill the current slot, or just type the first letters of its name and press Enter to drop it in, which is the fastest way to log an enemy's ban or pick without hunting the grid. Tapping a suggestion does the same thing as tapping the brawler. If you mis-tap, click the filled slot to clear it, and Reset clears the whole board between games.\n\nThe practical rhythm is: enter bans as they land, enter the enemy's pick the moment it appears, then read the top of the suggestion list for your own seat. The list changes meaningfully once enemies are on the board, because the counter signal only activates when there is someone to counter." },
    { heading: "Is it free?", body: "Yes. There is no account, no sign-in, no paid tier, and nothing is gated. The site may show a single ad, placed below the entire draft flow rather than beside the picker, so it cannot interfere with drafting.\n\nIt is unofficial fan content. It is not affiliated with, endorsed by, or sponsored by Supercell." },
    { heading: "Do I need to enter my player tag?", body: "No. The board works fully without one, and without a tag it gives you the population meta for the map you selected.\n\nEntering a tag unlocks four things. It resolves your Ranked tier, which decides whether the board shows you a blind-pick layout or a full snake draft. It switches the statistics to your rank bracket where there is enough data to build a separate table for that bracket. It loads your roster, which powers personalization — a separate column of your own best picks at Diamond and below, or the pick you mark as yours in the snake draft. And it folds in your own win rates with each brawler, computed from ranked matches you appear in, so a brawler you personally do well on gets nudged up.\n\nYour own win rates are handled conservatively. A thin personal sample is shrunk heavily toward the population rate, and the weight the personal signal carries scales with how many games you actually have on that brawler, so two games barely moves anything." },
    { heading: "Where is my tag stored, and how do I get rid of it?", body: "In your own browser's local storage, under a single key, so the board remembers you next visit. It is sent to the server to perform the lookups described above, and that is all it is used for.\n\nThere is an X button inside the tag field. Clicking it clears the field, drops the rank badge, and deletes the saved value, so your next visit starts blank. Player tags are public identifiers in Brawl Stars and are not linked to names, emails, or anything else. The privacy page has the full detail." },
    { heading: "Why does the board look different at different ranks?", body: "Because Brawl Stars runs two different drafts. At Diamond and below (including Bronze, Silver, and Gold) drafting is blind: there is a ban phase, then you pick your own team without ever seeing the enemy's picks. There is no snake order and no counter-picking. From Mythic up you get the full reveal-and-counter draft on a 1-2-2-1 snake.\n\nWhen your tag resolves to Diamond or below, the board hides the enemy team entirely, drops the first-pick toggle, and shows a blind-pick badge. Suggestions then optimize your own composition on that map, since there is nothing to counter. The pick suggestions also split into two columns there: the map's meta picks beside your own best picks, filtered to what you can field. Everyone on the team picks at the same time in a blind draft, so there is no seat to mark — the personal column is simply always on. From Mythic up you get the enemy zone, the first-pick toggle, and counter-aware scoring.\n\nWithout a tag the board defaults to the full snake draft. If you are in a blind bracket, enter your tag so the layout matches what you are actually looking at in game." },
    { heading: "How does the tool account for the rest of the draft?", body: "Every candidate is scored on the board exactly as it stands — your picks so far, the enemy picks revealed so far, the map, and the mode. The win-probability model is trained on drafts with hidden slots, so an unfinished board is something it understands natively: its number reflects how real ranked drafts with those exact brawlers locked in typically finished. The remaining picks aren't filled in with guesses; their uncertainty is part of the number.\n\nThat is an average over how real opponents actually continued such drafts — not a simulation of a perfect opponent finding your sharpest counter. Thinking about what you expose yourself to when you pick early is still your job (the guide's seat-position section covers it).\n\nEarlier versions had a Deep search toggle that ran a minimax lookahead against an optimally-countering enemy. It was retired: it ranked picks from a crude five-candidate shortlist, ignored your roster and personal history, and assumed everyone — opponents and teammates alike — plays perfectly. The model's built-in read is calibrated against a million real games instead, and it is always on, in every bracket including blind pick." },
    { heading: "How do I personalize the board to my account, and why is it sometimes greyed out?", body: "How you personalize depends on your bracket's draft format. From Mythic up, under Your team there is an \"I'm pick\" selector — mark which of your team's three picks, in pick order, is actually you. Only that pick is personalized; the other two are teammates whose collections aren't yours, so they stay on the full meta. On your pick, suggestions are restricted to brawlers you can actually field — ones you own, plus this season's free \"boosted\" brawlers that everyone can use in Ranked — and the recommendation cards gain a mastery bar plus tags for what is missing, such as no star power, no gadget, or no hypercharge. In the picker, brawlers you can't field are dimmed, and the free boosted ones carry a small FREE badge.\n\nAt Diamond and below there is no selector, because there is no pick order — the whole team picks at once. Instead, once your tag loads, the pick suggestions split into two columns: the map's meta picks on one side, and your own best picks on the other, filtered to what you can field and weighted by your mastery and your own record. The brawler picker stays unfiltered there, since you log your teammates' picks from it too.\n\nThe mastery score is deliberately loadout-forward. It is mostly build completeness (star power, gadget, and gears) and partly comfort, measured from your highest trophies on the brawler. Power level is handled upstream as a hard filter rather than a score: Ranked blocks selecting a brawler below Power 9 through Diamond, or below Power 11 from Mythic up, and the board folds that floor into the same can-you-field-it check as ownership. Every brawler you are actually offered already clears it, so the score measures what still separates them — the star powers, gadgets, and gears you own, and how much you have played them. A free boosted brawler you don't own counts as fully built but with no comfort, since you have no history on it.\n\nBoth forms wait for a roster to load: the selector stays greyed out and the personal column doesn't appear until then. That requires a resolved player tag and a successful roster lookup. Enter your tag, wait for the rank badge to appear, and personalization switches on." },
    { heading: "What is the Top Meta / full loadout strip, and why doesn't it match my recommendations?", body: "The compact icon strip, labelled Top Meta, is the pure population meta for the board in front of you. It answers a different question from the main list: not what should you pick, but who is simply strongest here right now.\n\nIt applies no roster filter at all and judges every brawler as if it had a complete loadout, all gadgets, gears, and star powers. It does track the live board, so brawlers that are picked or banned drop out and synergy with your team and counters to theirs fold into the ranking, but it never personalizes.\n\nSo the two lists diverge exactly where personalization bites — on your own pick. If a brawler is high on the strip and absent from your recommendations there, it usually means you do not own it and it is not one of the season's free brawlers, or you own it half-built, or your own record on it is poor. That gap is useful information: it is a shortlist of what would most improve your drafting if you invested in it." },
    { heading: "What do the signal bars mean?", body: "Each bar is one signal, expressed as a win-rate-like number so they are directly comparable. Map is the brawler's win rate on that specific map. Synergy is its average pairing with the allies you have locked. Counter is its average matchup against the enemies revealed so far. Role is how well its class fits the mode. Model is the win-probability net's read of the board as it stands — it is trained on unfinished drafts, so slots not yet picked stay honestly unknown. Mastery and you are the personal signals — they appear on the pick you've marked as your seat in the snake draft, or in the personal column at Diamond and below: mastery is your build investment, you is your own win rate with that brawler.\n\nThe bars are zoomed to roughly the 35 to 65 percent range rather than 0 to 100. Real ranked win rates cluster tightly around 50 percent, so a full-scale bar would make every brawler look identical.\n\nThe top recommendation shows the full set as bars; the runners-up condense them to the strongest few as inline numbers. The signals are combined as a weighted average over only the ones currently active, then renormalized, which is why fewer bars show early in the draft. The model carries the largest weight, then map, then counter, then role, with synergy smallest. Those weights came from a held-out ablation, not from taste." },
    { heading: "What does confidence mean on a suggestion?", body: "It is how much data stands behind that number. Every raw win rate is smoothed toward a neutral prior using a pseudo-count of twenty games, and confidence is simply how far the real sample has pulled the estimate away from that prior. About twenty effective games reads as fifty percent confidence.\n\nSample is also recency-weighted, with a half-life of about three weeks, so a match from a month ago counts roughly a third of a fresh one. A brawler that fell out of the rotation after a nerf sheds effective sample, and therefore confidence, on its own.\n\nPractically: treat a high-scoring pick with low confidence as a suggestion rather than a read. It is a brawler with a small number of recent games on that map, not an established one." },
    { heading: "How does it choose bans?", body: "Ban suggestions are ranked by threat on the selected map, which is mostly the brawler's win rate there with a smaller contribution from how often it is picked. A brawler that wins a lot but nobody plays is less urgent to ban than one that is both strong and contested, because the contested one is far more likely to actually show up.\n\nThe ban cards show both numbers, win rate and use rate, so you can make the call yourself when the list is close. The official API never exposes the ban phase of collected matches, only the final picked teams, so ban value is inferred from win rate and contest rate rather than learned from what real players banned." },
    { heading: "Where does the data come from, and how current is it?", body: "From the official Brawl Stars API. That API is player-centric, meaning there is no global feed of matches, so a crawler snowballs outward: it seeds from top players, reads their recent ranked battles, harvests the other five player tags from each match, and repeats. Matches are deduplicated by a stable key, since one game shows up in as many as six players' logs.\n\nCollection runs continuously, and the live site re-syncs the published data roughly every ten minutes, rebuilding its statistics and reloading the model without restarting. The match counter in the header shows the current dataset size.\n\nStatistics are recency-weighted throughout, so the numbers lean on recent games rather than treating a match from three months ago as equally informative." },
    { heading: "What happens after a balance change?", body: "Two things, one gradual and one automatic. The gradual one is the recency weighting: because old matches decay, the statistics drift toward the new reality on their own within a few weeks of any change.\n\nThe automatic one is faster. A drift check compares each brawler's win rate over the last seven days against the previous seven and flags any move too large to be sampling noise, using a two-proportion z-test with a deliberately conservative threshold and a minimum of thirty games in each window. It also watches for brawler IDs appearing in play that are not in the reference data yet, which is a reliable marker that an update shipped.\n\nWhen that check trips, the win-probability model retrains on fresh data and the live site swaps in the new one on its next refresh. You will also see a yellow banner on the board naming the brawlers that moved, which is your cue that the numbers are mid-correction and worth a bit of skepticism for a few days." },
    { heading: "How accurate is the model?", body: "The current win-probability model was built from roughly 990,000 ranked matches, with about 148,000 of them held out for validation — so the numbers below come from matches it never saw. On that held-out set it reaches an AUC of 0.627 and 58.9 percent accuracy, against 0.571 AUC for a logistic-regression baseline built on brawler presence alone.\n\nThe more important number is calibration: expected calibration error is about 0.01, meaning when it says sixty percent, teams in that bucket win about sixty percent of the time. For a tool that consumes probabilities and compares them, being honest about the odds matters more than raw accuracy.\n\nThose numbers should also be read as a ceiling on what drafting can do. Ranked matchmaking pairs teams of similar skill, and most of the result is decided by how the game is played. A held-out ablation over about 40,000 matches found the draft signal varies by mode, strongest in Heist and weakest in Knockout, which is a useful thing to know in itself: in Heist, drafting well buys you more than it does in Knockout." },
    { heading: "Why isn't my map in the dropdown?", body: "The map list only includes maps that appear in the collected ranked data, sorted by mode. A map that just entered rotation may take a little while to accumulate enough games to show up, and maps that left rotation eventually stop appearing.\n\nIf your exact map is missing, pick the closest map in the same mode. Mode-level effects, which class the mode rewards and how compositions are shaped, carry most of the way; the map-specific win rates are the part you lose." },
    { heading: "Is the newest brawler included?", body: "Usually within a short window, but not instantly. A brand-new brawler is detected automatically when it starts appearing in collected matches, and the reference data and model are updated in response.\n\nEven once it appears, treat its numbers carefully for the first stretch. A new release needs enough recent ranked games before its win rate, synergies, and matchups mean anything, and the confidence figure on the card will tell you honestly when that has not happened yet." },
    { heading: "Why did the site take a while to load the first time?", body: "The backend runs on a free hosting tier that spins the server down after about fifteen minutes with no traffic. Waking it back up, loading the model and rebuilding the statistics, takes roughly thirty to forty-five seconds. That is why you may see a waking up the draft server message on a first visit.\n\nOnce it is warm it stays fast, and reloads are near-instant. The board retries in the background rather than showing an error, so the right move is to wait it out. If it genuinely cannot reach the server it will say so and offer a retry button." },
    { heading: "Does it work for Showdown or other modes?", body: "No. It covers Ranked only, which means the six ranked modes: Gem Grab, Brawl Ball, Knockout, Hot Zone, Heist, and Bounty.\n\nEverything the tool does assumes a 3v3 draft with bans, two fixed teams, and a known map. Showdown, Duo Showdown, and the rotating event modes have none of that structure, so the model and the statistics simply do not apply to them." },
    { heading: "Will this make me win more?", body: "Honestly: it is a small edge, and only if you draft well with it. Drafting is a real factor in Ranked but not the dominant one. Matchmaking pairs comparable teams, and the majority of the outcome is how the match is played, not what was on the loading screen.\n\nThe tool cannot and does not measure your win rate, so no claim about improvement is being made here. What it reliably does is stop the avoidable losses: taking a brawler that is weak on that specific map, leaving your comp with no frontline or no long range, walking into an obvious counter, or first-picking something that hands the enemy an easy answer.\n\nThe biggest gains tend to come from the boring parts. Learn which of your brawlers are genuinely strong on the maps currently in rotation, finish the loadouts on the ones you actually draft, and stop banning by reputation instead of by what is strong right now." },
    { heading: "Is using it allowed? Could I get banned?", body: "It reads publicly available match data through the official Brawl Stars API, the same information you can see in your own in-game battle log. It does not connect to, modify, automate, or interact with the game client in any way. Nothing about using it touches your game session.\n\nIt is a reference you look at, in the same category as a map guide or a tier list. It is unofficial fan content published under Supercell's Fan Content Policy." },
    { heading: "Is this affiliated with Supercell?", body: "No. This site is unofficial fan content and is not affiliated with, endorsed, sponsored, or specifically approved by Supercell, and Supercell is not responsible for it. Brawl Stars is a trademark of Supercell Oy.\n\nReference data and brawler images come from the official Brawl Stars API and from Brawlify." },
  ],
};

export default function Page() {
  return <ContentPage content={content} current="/faq" />;
}
